### ISSUE TITLE
PowerZero 

### ISSUE THREAD

**Issue by Blueforcer** [tomquist/esphome-b2500#13]
Hallo,

bei der nulleinspeisung scheint der max WR output mit 600watt angegeben zu sein,
Meiner macht allerdings 800W wodurch die umrechnung nicht mehr genau stimmt.
Evtl kann man das im Konfigurator noch einstellbar machen

mfg
Blueforcer

**Comment by tomquist** [comment]
In v2 gibt es jetzt eine config dafür, die zur Laufzeit verändert werden kann.
