### ISSUE TITLE
Beta V2 :  Temperaturen des Speichers werden nicht ausgegeben

### ISSUE THREAD

**Issue by knickohr** [tomquist/esphome-b2500#18]
Die Temperaturen Temp1 und Temp2 vom Speicher werden bei der neuen Beta nicht mehr über MQTT ausgegeben. Es steht immer 0 drin. Ob es im Webserver auch so ist habe ich nicht kontrolliert, habe den Webserver deaktiviert.

**Comment by tomquist** [comment]
Ist jetzt behoben

**Comment by knickohr** [comment]
👍
