### ISSUE TITLE
Artifact Error

### ISSUE THREAD

**Issue by qwikser** [tomquist/esphome-b2500#22]
Hallo - beim Image erstellen bekomme ich immer diese Meldung ([build_esphome](https://github.com/tomquist/esphome-b2500/actions/runs/10817527800/job/30011105886#step:1:24)
This request has been automatically failed because it uses a deprecated version of actions/upload-artifact: v2. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/)

..hatte es vor 2 Tagen zum Test mit einem Test Wifi & MQTT versucht, dass muss ich aber jetzt ändern. Oder kann ich die CFG auch ohne neues Build anpassen irgendwo? :)

MfG.
Daniel

**Comment by tomquist** [comment]
Danke für die Meldung! Sollte jetzt behoben sein.
