### ISSUE TITLE
Build mit esp32-s3 schlägt fehl

### ISSUE THREAD

**Issue by airzl** [tomquist/esphome-b2500#23]
Ein build einer Firmware mit platform esp32s3 und 16MB schlägt fehlt. Auto und 16 MB funktionierte

**Comment by airzl** [comment]
https://github.com/tomquist/esphome-b2500/actions/runs/11021927910

**Comment by tomquist** [comment]
Der Build schlägt fehl, weil das eingegebene Board kein esp32s3 ist:
> Option 'variant' does not match selected board.
