### ISSUE TITLE
Neue B2500 Firmware (V218.10) und App Versionen (V1.5.10) mit 5 Zeitintervallen

### ISSUE THREAD

**Issue by utulo** [tomquist/esphome-b2500#45]
Die neuesten B2500 Firmware (V218.10) und App Versionen (V1.5.10) haben 5 Zeitintervalle zur output Steuerung. Ist dies im esphome-b2500.yaml schon berücksichtigt? konnte es bisher nicht finden. kann jemand helfen?

**Comment by tomquist** [comment]
Ja, wird seit ca 2 Tagen unterstützt. Einfach ein neues Image bauen

**Comment by utulo** [comment]
Vielen Dank!!!

 

Von: Tom Quist ***@***.***> 
Gesendet: Samstag, 21. Dezember 2024 15:11
An: tomquist/esphome-b2500 ***@***.***>
Cc: utulo ***@***.***>; Author ***@***.***>
Betreff: Re: [tomquist/esphome-b2500] Neue B2500 Firmware (V218.10) und App Versionen (V1.5.10) mit 5 Zeitintervallen (Issue #45)

 

Ja, wird seit ca 2 Tagen unterstützt. Einfach ein neues Image bauen
