### ISSUE TITLE
Frage zur Temperatur

### ISSUE THREAD

**Issue by DjLex2021** [tomquist/esphome-b2500#53]
Hi @tomquist 

ich habe mal eine Frage zur angezeigten Temperatur.
Wie wird diese ermittelt bzw. errechnet?

Ich habe das Problem, wenn die Temperatur unter 0 sinkt, er mir 65.535 Grad anzeigt.
Hast du eine Idee, woran das liegt?

VG
Alex

**Comment by DjLex2021** [comment]
Ich hab die Commits doch durchgeschaut... wie konnte ich das übersehen?
Danke für deine Antwort und sorry für die Störung!

**Comment by tomquist** [comment]
Kein problem!
